---
name: 'Semantic Versioning'
description: 'Applying semantic versioning to your repo project'
inputs:
  versioning-type: # id of input
    description: 'Provide a versioning type (major, minor, patch)'
    required: true
    default: 'patch'
outputs:
  new-version:
    description: 'Incremented version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.versioning-type }}